#region MIT License
// <copyright company = "Edgerunner.org" file = "LexerErrorListener.cs">
// Copyright(c) Thaddeus Ryker 2025
// </copyright>
// The MIT License (MIT)
// 
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
// 
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
// 
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
#endregion

using Antlr4.Runtime;
using System.Collections.Generic;

namespace Org.Edgerunner.Language.AL.Parsing.Messaging
{
   /// <summary>
   /// Class that represents an ANTLR error listener.
   /// Implements the <see cref="int" />
   /// </summary>
   /// <seealso cref="int" />
   internal class LexerErrorListener : IAntlrErrorListener<int>
   {
      /// <summary>
      /// Initializes a new instance of the <see cref="LexerErrorListener"/> class.
      /// </summary>
      /// <param name="source">The source.</param>
      public LexerErrorListener(MessageSource source)
      {
         Source = source;
         Messages = new List<ErrorMessage>();
      }

      /// <summary>
      /// Gets the message source.
      /// </summary>
      /// <value>The source.</value>
      public MessageSource Source { get; }

      /// <summary>
      /// Gets or sets the messages.
      /// </summary>
      /// <value>The messages.</value>
      public List<ErrorMessage> Messages { get; set; }

      /// <summary>
      /// Upon syntax error, notify any interested parties.
      /// </summary>
      /// <param name="recognizer">What parser got the error. From this
      /// object, you can access the context as well
      /// as the input stream.</param>
      /// <param name="offendingSymbol">The offending token in the input token
      /// stream, unless recognizer is a lexer (then it's null). If
      /// no viable alternative error,
      /// <paramref name="e" />
      /// has token at which we
      /// started production for the decision.</param>
      /// <param name="line">The line number in the input where the error occurred.</param>
      /// <param name="charPositionInLine">The character position within that line where the error occurred.</param>
      /// <param name="msg">The message to emit.</param>
      /// <param name="e">The exception generated by the parser that led to
      /// the reporting of an error. It is null in the case where
      /// the parser was able to recover in line without exiting the
      /// surrounding rule.</param>
      /// <remarks>Upon syntax error, notify any interested parties. This is not how to
      /// recover from errors or compute error messages.
      /// <see cref="T:Antlr4.Runtime.IAntlrErrorStrategy" />
      /// specifies how to recover from syntax errors and how to compute error
      /// messages. This listener's job is simply to emit a computed message,
      /// though it has enough information to create its own message in many cases.
      /// <p>The
      /// <see cref="T:Antlr4.Runtime.RecognitionException" />
      /// is non-null for all syntax errors except
      /// when we discover mismatched token errors that we can recover from
      /// in-line, without returning from the surrounding rule (via the single
      /// token insertion and deletion mechanism).</p></remarks>
      // ReSharper disable once TooManyArguments
      public void SyntaxError(IRecognizer recognizer,
                              int offendingSymbol,
                              int line,
                              int charPositionInLine,
                              string msg,
                              RecognitionException e)
      {
         Messages.Add(new ErrorMessage(Source, MessageSeverity.Error, line, charPositionInLine, msg));
      }
   }
}