parser grammar ALCoreParser;

options { tokenVocab=ALLexer; }

/*
 * Generic constructs
 */

identifier
   : IDENTIFIER
   | ABS
   | ACTION
   | ACTIONREF
   | ACTIVATE
   | ACTIVE
   | ACTIVECONTROLONOPEN
   | ADDLINK
   | ADDTEXT
   | ALTSEARCHFIELD
   | APPLICATIONPATH
   | ARRAY
   | ARRAYLEN
   | ASCENDING
   | ASSERTERROR
   | ASSISTEDIT
   | AUDITCATEGORY
   | AUTOCALCFIELD
   | AUTOENTER
   | AUTOFORMATEXPR
   | AUTOFORMATTYPE
   | AUTOINCREMENT
   | AUTOMATION
   | AUTOPOSITION
   | AUTOREPEAT
   | AUTOREPLACE
   | AUTOSAVE
   | AUTOSPLITKEY
   | AUTOUPDATE
   | AVERAGE
   | BACKCOLOR
   | BACKTRANSPARENT
   | BACKUPKEY
   | BEEP
   | BEGIN
   | BIGINTEGER
   | BIGTEXT
   | BINARY
   | BITMAP
   | BITMAPLIST
   | BITMAPPOS
   | BLANKNUMBERS
   | BLANKZERO
   | BLOB
   | BOOLEAN
   | BORDER
   | BORDERCOLOR
   | BORDERSTYLE
   | BORDERWIDTH
   | BOTTOMMARGIN
   | BREAK
   | BYTE
   | CALCDATE
   | CALCFIELD
   | CALCFIELDS
   | CALCFORMULA
   | CALCSUM
   | CALCSUMS
   | CALLFIELDVALIDATE
   | CANCEL
   | CAPTION
   | CAPTIONBAR
   | CAPTIONCLASS
   | CAPTIONML
   | CARDPAGEID
   | CASE
   | CHANGECOMPANY
   | CHAR
   | CHARALLOWED
   | CHARTPARTID
   | CHECKLICENSEFILE
   | CLASS
   | CLEAR
   | CLEARALL
   | CLEARLASTERROR
   | CLEARMARKS
   | CLEARONLOOKUP
   | CLIENTTYPE
   | CLOSE
   | CLOSINGDATE
   | CLOSINGDATES
   | CLUSTERED
   | CODE
   | CODECOVERAGELOG
   | CODEUNIT
   | COMMANDLINE
   | COMMIT
   | COMMITBEHAVIOR
   | COMPANYNAME
   | COMPLETIONTRIGGERERRORLEVEL
   | COMPRESSARRAY
   | COMPRESSED
   | CONFIRM
   | CONNECTIONTYPE
   | CONSISTENT
   | CONST
   | CONTAINERTYPE
   | CONTEXTURL
   | CONTINUE
   | CONTROLADDIN
   | CONTROLTYPE
   | CONVERTSTR
   | COPY
   | COPYARRAY
   | COPYFILTER
   | COPYFILTERS
   | COPYLINKS
   | COPYSTR
   | COPYSTREAM
   | COUNT
   | COUNTAPPROX
   | CREATE
   | CREATEDATETIME
   | CREATEGUID
   | CREATEINSTREAM
   | CREATEOUTSTREAM
   | CREATETEMPFILE
   | CURRENTDATETIME
   | CURRENTEXECUTIONMODE
   | CURRENTKEY
   | CURRENTKEYINDEX
   | CURRENTTRANSACTIONTYPE
   | CURRPAGE
   | CURRREPORT
   | CUSTOMACTION
   | DATABASE
   | DATACAPTIONEXPR
   | DATACAPTIONFIELDS
   | DATACLASSIFICATION
   | DATAITEMINDENT
   | DATAITEMLINK
   | DATAITEMLINKREFERENCE
   | DATAITEMSEPARATOR
   | DATAITEMTABLE
   | DATAITEMTABLEVIEW
   | DATALENGTH
   | DATAPERCOMPANY
   | DATASCOPE
   | DATATRANSFER
   | DATE
   | DATE2DMY
   | DATE2DWY
   | DATEFORMULA
   | DATETIME
   | DATI2VARIANT
   | DEBUGGER
   | DECIMAL
   | DECIMALPLACES
   | DECIMALPLACESMAX
   | DECIMALPLACESMIN
   | DEFAULT
   | DEFAULTFIELDSVALIDATION
   | DEFAULTLAYOUT
   | DELAYEDINSERT
   | DELCHR
   | DELETE
   | DELETEALL
   | DELETEALLOWED
   | DELETELINK
   | DELETELINKS
   | DELSTR
   | DESCRIPTION
   | DEVICEFONTNAME
   | DIALOG
   | DICTIONARY
   | DIMENSIONS
   | DIRECTION
   | DIVISOR
   | DMY2DATE
   | DO
   | DOTNET
   | DOTNETASSEMBLY
   | DOTNETTYPEDECLARATION
   | DOWNLOAD
   | DOWNLOADFROMSTREAM
   | DOWNTO
   | DRILLDOWN
   | DRILLDOWNPAGEID
   | DROPDOWN
   | DT2DATE
   | DT2TIME
   | DUPLICATE
   | DURATION
   | DWY2DATE
   | EDITABLE
   | ELLIPSIS
   | ELSE
   | ENABLED
   | ENABLEDIFERROR
   | ENABLEDIFINSERTION
   | ENABLEDIFSELECTION
   | ENCODING
   | END
   | ENTITLEMENT
   | ENUM
   | ENUMEXTENSION
   | ENVIRON
   | EOS
   | ERASE
   | ERROR
   | ERRORBEHAVIOR
   | ERRORCONTEXT
   | ERRORINFO
   | ERRORTYPE
   | EVALUATE
   | EXECUTIONCONTEXT
   | EXECUTIONMODE
   | EVENT
   | EXIST
   | EXISTS
   | EXIT
   | EXPORT
   | EXPORTOBJECTS
   | EXTENDEDDATATYPE
   | EXTENDS
   | FIELD
   | FIELDACTIVE
   | FIELDCAPTION
   | FIELDCLASS
   | FIELDCOUNT
   | FIELDENDDELIMITER
   | FIELDERROR
   | FIELDEXIST
   | FIELDGROUP
   | FIELDGROUPS
   | FIELDINDEX
   | FIELDNAME
   | FIELDNO
   | FIELDREF
   | FIELDSEPARATOR
   | FIELDTYPE
   | FIELDSTARTDELIMITER
   | FIELDVALIDATE
   | FILE
   | FILEFORMAT
   | FILENAME
   | FILTER
   | FILTERGROUP
   | FILTERPAGEBUILDER
   | FIND
   | FINDFIRST
   | FINDLAST
   | FINDSET
   | FOCUSABLE
   | FOCUSONCLICK
   | FONTBOLD
   | FONTITALIC
   | FONTNAME
   | FONTSIZE
   | FONTSTRIKETHRU
   | FONTUNDERLINE
   | FOR
   | FOREACH
   | FORECOLOR
   | FORMAT
   | FREEZECOLUMNID
   | FUNCTION
   | FUNCTIONTYPE
   | GET
   | GETFILTER
   | GETFILTERS
   | GETLASTERRORTEXT
   | GETPOSITION
   | GETRANGEMAX
   | GETRANGEMIN
   | GETRECORD
   | GETSTAMP
   | GETSUBTEXT
   | GETTABLE
   | GETURL
   | GETVIEW
   | GLOBALLANGUAGE
   | GROUPTOTALFIELDS
   | GROUPTYPE
   | GUIALLOWED
   | GUID
   | HANDLERFUNCTIONS
   | HASFILTER
   | HASLINKS
   | HASVALUE
   | HEADINGHEIGHT
   | HEIGHT
   | HIDEVALUE
   | HORZALIGN
   | HORZGLUE
   | HORZGRID
   | HTTPCONTENT
   | HTTPHEADERS
   | HTTPCLIENT
   | HTTPREQUESTMESSAGE
   | HTTPRESPONSEMESSAGE
   | HYPERLINK
   | ID
   | IF
   | IMAGE
   | IMPLEMENTS
   | IMPORT
   | IMPORTANCE
   | IMPORTOBJECTS
   | IN
   | INCLUDEINDATASET
   | INCOLUMN
   | INCOLUMNHEADING
   | INCSTR
   | INDATASET
   | INDENT
   | INDENTATION
   | INDENTATIONCOLUMNNAME
   | INDENTATIONCONTROLS
   | INFOOTERBAR
   | INFRAME
   | INHERENTPERMISSIONSSCOPE
   | INIT
   | INITVALUE
   | INLINEEDITING
   | INMATRIX
   | INMATRIXHEADING
   | INPAGE
   | INPUT
   | INSERT
   | INSERTALLOWED
   | INSSTR
   | INSTREAM
   | INSTRUCTIONALTEXTML
   | INTEGER
   | INTERFACE
   | INTERNAL
   | INVALIDACTIONAPPEARANCE
   | ISACTION
   | ISAUTOMATION
   | ISBINARY
   | ISBOOLEAN
   | ISCHAR
   | ISCLEAR
   | ISCODE
   | ISCODEUNIT
   | ISDATE
   | ISDATEFORMULA
   | ISDECIMAL
   | ISEMPTY
   | ISFILE
   | ISINSTREAM
   | ISINTEGER
   | ISNULLGUID
   | ISOLATIONLEVEL
   | ISOPTION
   | ISOUTSTREAM
   | ISRECORD
   | ISTEXT
   | ISTIME
   | ISTRANSACTIONTYPE
   | JOKER
   | JSONTOKEN
   | JSONVALUE
   | JSONARRAY
   | JSONOBJECT
   | KEEPWITHNEXT
   | KEY
   | KEYCOUNT
   | KEYGROUPDISABLE
   | KEYGROUPENABLE
   | KEYGROUPENABLED
   | KEYGROUPS
   | KEYINDEX
   | KEYREF
   | LABEL
   | LANGUAGE
   | LEADERDOTS
   | LEFTMARGIN
   | LEN
   | LENGTH
   | LINKEDINTRANSACTION
   | LINKEDOBJECT
   | LINKFIELDS
   | LINKSALLOWED
   | LINKTABLE
   | LINKTABLEFORCEINSERT
   | LIST
   | LOCAL
   | LOCKTABLE
   | LOCKTIMEOUT
   | LOGHEIGHT
   | LOGWIDTH
   | LOOKUP
   | LOOKUPMODE
   | LOOKUPPAGEID
   | LOWERCASE
   | MAINTAINSIFTINDEX
   | MAINTAINSQLINDEX
   | MARK
   | MARKEDONLY
   | MATRIXCOLUMNWIDTH
   | MATRIXSOURCETABLE
   | MAX
   | MAXIMIZABLE
   | MAXIMIZEDONOPEN
   | MAXITERATION
   | MAXLENGTH
   | MAXOCCURS
   | MAXSTRLEN
   | MAXVALUE
   | MEDIA
   | MEDIASET
   | MENUITEMTYPE
   | MENULEVEL
   | MESSAGE
   | MIN
   | MINIMIZABLE
   | MINIMIZEDONOPEN
   | MINOCCURS
   | MINVALUE
   | MODIFY
   | MODIFYALL
   | MODIFYALLOWED
   | MODULEDEPENDENCYINFO
   | MODULEINFO
   | MULTILINE
   | MULTIPLENEWLINES
   | NAME
   | NAMESPACE
   | NEWPAGEPERGROUP
   | NEXT
   | NEXTCONTROL
   | NODENAME
   | NODETYPE
   | NONE
   | NOTIFICATION
   | NOTIFICATIONSCOPE
   | NORMALDATE
   | NOTBLANK
   | NUMBER
   | NUMERIC
   | OBJECTTYPE
   | OCCURRENCE
   | OCX
   | OF
   | ONACTION
   | ONACTIVATE
   | ONAFTERASSIGNFIELD
   | ONAFTERASSIGNVARIABLE
   | ONAFTEREXPORTRECORD
   | ONAFTERFORMATFIELD
   | ONAFTERGETFIELD
   | ONAFTERGETRECORD
   | ONAFTERIMPORTRECORD
   | ONAFTERINITRECORD
   | ONAFTERINPUT
   | ONAFTERINSERTRECORD
   | ONAFTERMODIFYRECORD
   | ONAFTERTESTRUN
   | ONAFTERVALIDATE
   | ONASSISTEDIT
   | ONBEFOREEVALUATEFIELD
   | ONBEFOREEXPORTRECORD
   | ONBEFOREIMPORTRECORD
   | ONBEFOREINPUT
   | ONBEFOREINSERTRECORD
   | ONBEFOREMODIFYRECORD
   | ONBEFOREPASSFIELD
   | ONBEFOREPASSVARIABLE
   | ONBEFOREPUTRECORD
   | ONBEFORETESTRUN
   | ONCLOSEPAGE
   | ONCONTROLADDIN
   | ONDEACTIVATE
   | ONDELETE
   | ONDELETERECORD
   | ONDRILLDOWN
   | ONFINDRECORD
   | ONFORMAT
   | ONINIT
   | ONINITREPORT
   | ONINITXMLPORT
   | ONINPUTCHANGE
   | ONINSERT
   | ONINSERTRECORD
   | ONLOOKUP
   | ONMODIFY
   | ONMODIFYRECORD
   | ONNEWRECORD
   | ONNEXTRECORD
   | ONOPENPAGE
   | ONPOSTDATAITEM
   | ONPOSTREPORT
   | ONPOSTSECTION
   | ONPOSTXMLPORT
   | ONPREDATAITEM
   | ONPREREPORT
   | ONPRESECTION
   | ONPREXMLITEM
   | ONPREXMLPORT
   | ONPUSH
   | ONQUERYCLOSEPAGE
   | ONRENAME
   | ONTIMER
   | ONVALIDATE
   | OPEN
   | OPTION
   | OPTIONCAPTION
   | OPTIONCAPTIONML
   | OPTIONSTRING
   | OPTIONVALUE
   | ORDER
   | ORIENTATION
   | OSVERSION
   | OUTSTREAM
   | PADCHAR
   | PADSTR
   | PAGE
   | PAGEBACKGROUNDTASKERRORLEVEL
   | PAGECUSTOMIZATION
   | PAGEEXTENSION
   | PAGENAMES
   | PAGENAMESML
   | PAGENO
   | PAGERESULT
   | PAGEPARTID
   | PAGETYPE
   | PAPERSIZE
   | PAPERSOURCE
   | PAPERSOURCEDEFAULTPAGE
   | PAPERSOURCEFIRSTPAGE
   | PAPERSOURCELASTPAGE
   | PAPERSOURCEOTHERPAGES
   | PARENTCONTROL
   | PARTTYPE
   | PASSWORDTEXT
   | PASTEISVALID
   | PERCENTAGE
   | PERMANENTASSIST
   | PERMISSIONOBJECTTYPE
   | PERMISSIONS
   | PERMISSIONSET
   | PERMISSIONSETEXTENSION
   | PLACEINBOTTOM
   | POPULATEALLFIELDS
   | POS
   | POWER
   | PREVIEW
   | PRINTONEVERYPAGE
   | PRINTONLYIFDETAIL
   | PROCEDURE
   | PROCESSINGONLY
   | PROFILE
   | PROGRAM
   | PROMOTED
   | PROMOTEDCATEGORY
   | PROMOTEDISBIG
   | PROTECTED
   | PROVIDERID
   | PUSHACTION
   | QUERY
   | QUERYREPLACE
   | QUIT
   | RANDOM
   | RANDOMIZE
   | READ
   | READCONSISTENCY
   | READPERMISSION
   | READTEXT
   | REC
   | RECORD
   | RECORDID
   | RECORDLEVELLOCKING
   | RECORDREF
   | RECORDSEPARATOR
   | RELATION
   | RENAME
   | REPEAT
   | REPORT
   | REPORTEXTENSION
   | REPORTFORMAT
   | REPORTLAYOUTTYPE
   | REQFILTERFIELDS
   | REQFILTERHEADING
   | REQFILTERHEADINGML
   | REQUESTOPTIONSPAGE
   | RESET
   | RIGHTMARGIN
   | ROUND
   | ROUNDDATETIME
   | ROWHEIGHT
   | RUN
   | RUNCOMMAND
   | RUNMODAL
   | RUNOBJECT
   | RUNONCLIENT
   | RUNPAGELINK
   | RUNPAGEONREC
   | RUNPAGEVIEW
   | SAVEASEXCEL
   | SAVEASHTML
   | SAVEASPDF
   | SAVEASXML
   | SAVECOLUMNWIDTHS
   | SAVECONTROLINFO
   | SAVEPOSANDSIZE
   | SAVERECORD
   | SAVEVALUES
   | SECRETTEXT
   | SECTIONHEIGHT
   | SECTIONWIDTH
   | SECURITYFILTER
   | SECURITYFILTERING
   | SECURITYOPERATIONRESULT
   | SEEK
   | SELECTLATESTVERSION
   | SELECTSTR
   | SERIALNUMBER
   | SESSIONSETTINGS
   | SETAUTOCALCFIELDS
   | SETCURRENTKEY
   | SETFILTER
   | SETPERMISSIONFILTER
   | SETPOSITION
   | SETRANGE
   | SETRECFILTER
   | SETRECORD
   | SETSELECTIONFILTER
   | SETSTAMP
   | SETTABLE
   | SETTABLEVIEW
   | SETVIEW
   | SHAPESTYLE
   | SHELL
   | SHORTCUTKEY
   | SHOWASTREE
   | SHOWCAPTION
   | SHOWPRINTSTATUS
   | SHOWSTATUS
   | SID
   | SIGNDISPLACEMENT
   | SINGLEINSTANCE
   | SIZABLE
   | SLEEP
   | SORTING
   | SOURCEEXPR
   | SOURCEFIELD
   | SOURCETABLE
   | SOURCETABLEPLACEMENT
   | SOURCETABLERECORD
   | SOURCETABLETEMPORARY
   | SOURCETABLEVIEW
   | SOURCETYPE
   | SQLINDEX
   | STARTPOS
   | STARTSESSION
   | STOPSESSION
   | STRCHECKSUM
   | STRLEN
   | STRMENU
   | STRPOS
   | STRSUBSTNO
   | STYLE
   | STYLEEXPR
   | SUBPAGELINK
   | SUBPAGEVIEW
   | SUBTYPE
   | SUM
   | SUMINDEXFIELDS
   | SUPPRESSDISPOSE
   | SYNCHRONIZEALLLOGINS
   | SYNCHRONIZESINGLELOGIN
   | SYSTEM
   | SYSTEMACTION
   | SYSTEMPARTID
   | TABLE
   | TABLEBOXID
   | TABLECAPTION
   | TABLECONNECTIONTYPE
   | TABLEDATA
   | TABLEEXTENSION
   | TABLEFILTER
   | TABLEIDEXPR
   | TABLENAME
   | TABLENO
   | TABLERELATION
   | TELEMETRYSCOPE
   | TEMPORARY
   | TEMPORARYPATH
   | TESTACTION
   | TESTFIELD
   | TESTPAGE
   | TESTPERMISSIONS
   | TESTREQUESTPAGE
   | TESTTABLERELATION
   | TEXT
   | TEXTBUILDER
   | TEXTCONST
   | TEXTENCODING
   | TEXTMODE
   | TEXTPOS
   | TEXTTYPE
   | THEN
   | TIME
   | TIMERINTERVAL
   | TITLE
   | TO
   | TODAY
   | TOOLTIP
   | TOOLTIPML
   | TOPLINEONLY
   | TOPMARGIN
   | TOTALFIELDS
   | TOTALSCAUSEDBY
   | TRANSACTIONMODEL
   | TRANSACTIONTYPE
   | TRANSFERFIELDS
   | TRIGGER
   | UNTIL
   | TRUNC
   | TYPE
   | UPDATE
   | UPDATECONTROLS
   | UPDATEEDITABLE
   | UPDATEFONTBOLD
   | UPDATEFORECOLOR
   | UPDATEINDENT
   | UPDATEONACTION
   | UPDATEONACTIVATE
   | UPDATESELECTED
   | UPLOAD
   | UPLOADINTOSTREAM
   | UPPERCASE
   | UPPERLIMIT
   | USEREQUESTPAGE
   | USERID
   | USESYSTEMPRINTER
   | USING
   | VALIDATE
   | VALIDATETABLERELATION
   | VALUE
   | VALUESALLOWED
   | VAR
   | VARIABLEACTIVE
   | VARIABLENAME
   | VARIANT
   | VARIANT2DATE
   | VARIANT2TIME
   | VERBOSITY
   | VERSION
   | VERTALIGN
   | VERTGLUE
   | VERTGRID
   | VIEW
   | VIEWS
   | VISIBLE
   | WEBSERVICEACTIONCONTEXT
   | WEBSERVICEACTIONRESULTCODE
   | WHERE
   | WHILE
   | WIDTH
   | WINDOWSLANGUAGE
   | WITH
   | WITHEVENTS
   | WORDDATE
   | WRITE
   | WRITEMODE
   | WRITEPERMISSION
   | WRITETEXT
   | XMLATTRIBUTE
   | XMLATTRIBUTECOLLECTION
   | XMLCOMMENT
   | XMLCDATA
   | XMLDECLARATION
   | XMLDOCUMENT
   | XMLDOCUMENTTYPE
   | XMLELEMENT
   | XMLNAMESPACEMANAGER
   | XMLNAMETABLE
   | XMLNODE
   | XMLNODELIST
   | XMLPORT
   | XMLPROCESSINGINSTRUCTION
   | XMLREADOPTIONS
   | XMLTEXT
   | XMLVERSIONNO
   | XMLWRITEOPTIONS
   | XPOS
   | XREC
   | YIELD
   | YPOS
   ;

namespaceIdentifier
   : identifier namespaceAccessor?
   ;

namespaceAccessor
   : PERIOD identifier namespaceAccessor?
   ;

objectId
   : simpleObjectId
   | qualifiedObjectId;

objectName
   : identifier
   ;

simpleObjectId
   : identifier
   | INTEGER_LITERAL;

qualifiedObjectId
   : namespaceIdentifier PERIOD identifier
   ;

booleanLiteral
   : TRUE
   | FALSE
   ;

numberLiteral
   : FLOAT_LITERAL
   | INTEGER_LITERAL
   ;

sizeDeclaration
   : LEFTBRACKET INTEGER_LITERAL RIGHTBRACKET
   ;

dimensions
   : INTEGER_LITERAL (COMMA INTEGER_LITERAL)*?
   ;

objectLiteral
   : (namespaceIdentifier PERIOD)? identifier
   ;

enumerationLiteral
   : objectLiteral SCOPE identifier
   ;

systemEnumerationLiteral
   : OBJECTTYPE SCOPE identifier #ObjectTypeLiteral
   | TRANSACTIONTYPE SCOPE identifier #TransactionTypeLiteral
   | EXECUTIONMODE SCOPE identifier #ExecutionModeLiteral
   | SECURITYFILTER SCOPE identifier #SecurityFilterLiteral
   | TEXTENCODING SCOPE identifier #TextEncodingLiteral
   | REPORTFORMAT SCOPE identifier #ReportFormatLiteral
   | DEFAULTLAYOUT SCOPE identifier #DefaultLayoutLiteral
   | CONNECTIONTYPE SCOPE identifier #ConnectionTypeLiteral
   | CLIENTTYPE SCOPE identifier #ClientTypeLiteral
   | COMMITBEHAVIOR SCOPE identifier #CommitBehaviorLiteral
   | DATASCOPE SCOPE identifier #DataScopeLiteral
   | DATACLASSIFICATION SCOPE identifier #DataClassificationLiteral
   | ACTION SCOPE identifier #ActionLiteral
   | AUDITCATEGORY SCOPE identifier #AuditCategoryLiteral
   | EXECUTIONCONTEXT SCOPE identifier #ExecutionContextLiteral
   | ERRORBEHAVIOR SCOPE identifier #ErrorBehaviorLiteral
   | ERRORTYPE SCOPE identifier #ErrorTypeLiteral
   | ERRORCONTEXT SCOPE identifier #ErrorContextLiteral
   | FIELDCLASS SCOPE identifier #FieldClassLiteral
   | FIELDTYPE SCOPE identifier #FieldTypeLiteral
   | INHERENTPERMISSIONSSCOPE SCOPE identifier #InherentPermissionsScopeLiteral
   | ISOLATIONLEVEL SCOPE identifier #IsolationLevelLiteral
   | NOTIFICATIONSCOPE SCOPE identifier #NotificationScopeLiteral
   | OBJECTTYPE SCOPE identifier #ObjectTypeLiteral
   | PAGEBACKGROUNDTASKERRORLEVEL SCOPE identifier #PageBackgroundTaskErrorLevelLiteral
   | PERMISSIONOBJECTTYPE SCOPE identifier #PermissionObjectTypeLiteral
   | REPORTLAYOUTTYPE SCOPE identifier #ReportLayoutTypeLiteral
   | SECURITYOPERATIONRESULT SCOPE identifier #SecurityOperationResultLiteral
   | TABLECONNECTIONTYPE SCOPE identifier #TableConnectionTypeLiteral
   | TELEMETRYSCOPE SCOPE identifier #TelemetryScopeLiteral
   | TESTPERMISSIONS SCOPE identifier #TestPermissionsLiteral
   | TRANSACTIONMODEL SCOPE identifier #TransactionModelLiteral
   | TRANSACTIONTYPE SCOPE identifier #TransactionTypeLiteral
   | VERBOSITY SCOPE identifier #VerbosityLiteral
   | WEBSERVICEACTIONRESULTCODE SCOPE identifier #WebServiceActionResultCodeLiteral
   | CODEUNIT SCOPE objectLiteral #CodeunitLiteral
   | PAGE SCOPE objectLiteral #PageLiteral
   | PAGEEXTENSION SCOPE objectLiteral #PageExtensionLiteral
   | QUERY SCOPE objectLiteral #QueryLiteral
   | REPORT SCOPE objectLiteral #ReportLiteral
   | XMLPORT SCOPE objectLiteral #XmlPortLiteral
   | DATABASE SCOPE objectLiteral #DatabaseLiteral
   | ENUM SCOPE objectLiteral #EnumLiteral
   | TESTPAGE SCOPE objectLiteral #TestPageLiteral
   | TESTREQUESTPAGE SCOPE objectLiteral #TestRequestPageLiteral
   ;

namespaceDeclaration
   : {TokenMatches("namespace")}? identifier namespaceIdentifier SEMICOLON;

usingDeclaration
   : {TokenMatches("using")}? identifier namespaceIdentifier SEMICOLON;

usingDeclarations
   : usingDeclaration+;