//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Org.Edgerunner.BC.AL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Org.Edgerunner.BC.AL.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The handler type must be a typeof AlParserRule.
        /// </summary>
        internal static string BadHandlerType {
            get {
                return ResourceManager.GetString("BadHandlerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entering {0}.
        /// </summary>
        internal static string EnteringParserRule {
            get {
                return ResourceManager.GetString("EnteringParserRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exiting {0}.
        /// </summary>
        internal static string ExitingParserRule {
            get {
                return ResourceManager.GetString("ExitingParserRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected &quot;true&quot; or &quot;false&quot;, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedBoolean {
            get {
                return ResourceManager.GetString("ExpectedBoolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid date, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedDate {
            get {
                return ResourceManager.GetString("ExpectedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid datetime, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedDatetime {
            get {
                return ResourceManager.GetString("ExpectedDatetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid decimal, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedDecimal {
            get {
                return ResourceManager.GetString("ExpectedDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid identifier, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedIdentifier {
            get {
                return ResourceManager.GetString("ExpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid integer, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedInteger {
            get {
                return ResourceManager.GetString("ExpectedInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected an option value, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedOptionValue {
            get {
                return ResourceManager.GetString("ExpectedOptionValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected identifier &quot;{0}&quot;, instead encountered: &quot;{1}&quot;.
        /// </summary>
        internal static string ExpectedSpecificIdentifier {
            get {
                return ResourceManager.GetString("ExpectedSpecificIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected symbol &quot;{0}&quot;, instead encountered: &quot;{1}&quot;.
        /// </summary>
        internal static string ExpectedSpecificSymbol {
            get {
                return ResourceManager.GetString("ExpectedSpecificSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid string, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedString {
            get {
                return ResourceManager.GetString("ExpectedString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected symbol, instead encountered: &quot;{1}&quot;.
        /// </summary>
        internal static string ExpectedSymbol {
            get {
                return ResourceManager.GetString("ExpectedSymbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected either {0}, instead encountered: &quot;{1}&quot;.
        /// </summary>
        internal static string ExpectedSymbolFromSet {
            get {
                return ResourceManager.GetString("ExpectedSymbolFromSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expected valid time, instead encountered: &quot;{0}&quot;.
        /// </summary>
        internal static string ExpectedTime {
            get {
                return ResourceManager.GetString("ExpectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected End of File.
        /// </summary>
        internal static string UnexpectedEof {
            get {
                return ResourceManager.GetString("UnexpectedEof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected identifier: &quot;{0}&quot;.
        /// </summary>
        internal static string UnexpectedIdentifier {
            get {
                return ResourceManager.GetString("UnexpectedIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encountered unexpected literal: &quot;{0}&quot;.
        /// </summary>
        internal static string UnexpectedLiteralValue {
            get {
                return ResourceManager.GetString("UnexpectedLiteralValue", resourceCulture);
            }
        }
    }
}
